server:
  port: 1489

spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: ${DB_DRIVER}
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

kafka:
  bootstrap-servers: localhost:9092
  topics:
    payment-create-requested: payment.create.requested
    payment-created: payment.created
    payment-status-changed: payment.status.changed
  consumer:
    group-id: payment-provider-group

app:
  payment:
    base-url: http://localhost:1489
    max-retries: 3
